spring:
  boot:
    message: Hola, desde el microservicio EMPLOYEE con Spring Cloud Bus
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/employee_db
    password: VinceCar@125
logging:
  level:
    org:
      hibernate:
        nodeValue: WARN
        orm:
          connections:
            pooling: WARN
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: '8081'
